import type { Metadata } from "next"
import { TComponentWithChildren } from "@/types/pages/layout"

import { Toaster } from "@/components/ui/sonner"
import { TailwindIndicator } from "@/components/utility/tw-monitor"
import { ThemeProvider } from "@/components/providers/theme"
import LoadingProgressBar from "@/components/utility/loading-progress-bar"
import ScrollingProgressBar from "@/components/utility/scrolling-progress-bar"

export const metadata: Metadata = {
  title: "A Template App",
  description: "Generated by create next app",
  icons: {
    // Web
    icon: "/favicon.ico",
    // Android
    shortcut: "favicon.ico",
    // iOS
    apple: "favicon.ico",
  },
}

export default function MainLayout({ children }: TComponentWithChildren) {
  return (
    <ThemeProvider>
      <LoadingProgressBar />
      <ScrollingProgressBar />
      {children}
      <TailwindIndicator />
      <Toaster />
    </ThemeProvider>
  )
}
