import { Suspense } from "react"
import type { Metadata } from "next"
import { TComponentWithChildren } from "@/types/pages/layout"
import { inter } from "@/styles/font"
import "@/styles/globals.css"
import { cn } from "@/lib/utils"
import SplashScreen from "@/components/layouts/splash-screen"

export const metadata: Metadata = {
  title: "A Template App",
  description: "Generated by create next app",
  icons: {
    // Web
    icon: "/favicon.ico",
    // Android
    shortcut: "favicon.ico",
    // iOS
    apple: "favicon.ico",
  },
}

export default function RootLayout({
  children,
}: Readonly<TComponentWithChildren>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, viewport-fit=cover"
      />
      <body
        className={cn(
          "min-h-screen min-w-full bg-background font-sans text-foreground antialiased",
          inter.className,
          // "scrollbar scrollbar-track-background scrollbar-thumb-primary-foreground scrollbar-corner-background scrollbar-thumb-rounded-full scrollbar-w-1.5 scrollbar-h-2"
          "scrollbar-none" // apply within component with: "scrollbar overflow-y-scroll"
        )}
      >
        <Suspense fallback={<SplashScreen />}>{children}</Suspense>
      </body>
    </html>
  )
}
